language: python
python:
    - "2.6"
    - "2.7"
    # - "3.4"
# command to install dependencies
env:
    - DJANGO=1.3
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6
    - DJANGO=1.7
    - DJANGO=1.8

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "2.6"
      env: DJANGO=1.8

    #- python: "3.4"
    #  env: DJANGO=1.3
    #- python: "3.4"
    #  env: DJANGO=1.4
    #- python: "3.4"
    #  env: DJANGO=1.5
    #- python: "3.4"
    #  env: DJANGO=1.6


install:
    - pip install -q --upgrade pip
    - pip install -q Django==$DJANGO;
    - pip install -q -e .

# command to run tests
script: nosetests
