language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
env:
  - DJANGO=1.8
  - DJANGO=1.7
  - DJANGO=1.6
  - DJANGO=1.5
  - DJANGO=1.4
  - DJANGO=1.3
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -q -e . --use-mirrors

# command to run tests
script: nosetests
